export const ACTION_START = "ACTION_START";

export const LOADING_APP_START = "LOADING_APP_START";
export const LOADING_APP_SUCCESS = "LOADING_APP_SUCCESS";
export const LOADING_APP_FAILED = "LOADING_APP_FAILED";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const GET_CONVERSATIONS_SUCCESS = "GET_CONVERSATIONS_SUCCESS";
export const GET_CONVERSATIONS_FAILED = "GET_CONVERSATIONS_FAILED";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";

export const ACTION_FAILED = "ACTION_FAILED";
